[colors-dark]
alpha=0.80
background=000000

[main]
# font=JetBrainsMonoNerdFont:size=11
# font-bold=JetBrainsMonoNerdFont:size=11
font= Maple Mono NF CN:size=11
font-bold= Maple Mono NF CN:size=11
pad=6x6
include=~/.config/foot/catppuccin-mocha.ini
login-shell=yes

[mouse]
hide-when-typing=yes

[scrollback]
lines=1000

[cursor]
style=block
blink=no

